### ISSUE TITLE
bug: EACCES error="Permission denied @ dir_s_mkdir

### ISSUE THREAD

**Issue by kaiohenricunha** [fluent/fluent-operator#735]
### Describe the issue

I'm getting "permission denied" error whenever I try to set a file buffer:

```
<buffer>
  @type file
  path /data/fluentd/buffer.log
  flush_mode interval
  flush_interval 10s
  flush_thread_count 8
  flush_at_shutdown true
  chunk_limit_size 256m
  total_limit_size 10g
  overflow_action throw_exception
  retry_max_times 5
  retry_wait 30s
  retry_exponential_backoff_base 2
  retry_max_interval 90
  compress gzip
</buffer>
 ```

The memory buffer, on the other hand, works just fine.

I've tried different paths like `/var/log/` and `/buffers/opensearch` and got the same error:

```bash
2023-05-15 14:13:11 +0000 [error]: #0 unexpected error error_class=Errno::EACCES error="Permission denied @ dir_s_mkdir - /var/log/fluentd"
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/3.1.0/fileutils.rb:240:in `mkdir'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/3.1.0/fileutils.rb:240:in `fu_mkdir'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/3.1.0/fileutils.rb:221:in `block (2 levels) in mkdir_p'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/3.1.0/fileutils.rb:219:in `reverse_each'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/3.1.0/fileutils.rb:219:in `block in mkdir_p'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/3.1.0/fileutils.rb:211:in `each'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/3.1.0/fileutils.rb:211:in `mkdir_p'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/buf_file.rb:122:in `start'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:476:in `start'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/event_loop.rb:85:in `start'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin_helper/timer.rb:54:in `start'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:203:in `block in start'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:182:in `block (2 levels) in lifecycle'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/agent.rb:121:in `block (2 levels) in lifecycle'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/agent.rb:120:in `each'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/agent.rb:120:in `block in lifecycle'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/agent.rb:113:in `each'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/agent.rb:113:in `lifecycle'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:181:in `block in lifecycle'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:178:in `each'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:178:in `lifecycle'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:202:in `start'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/engine.rb:248:in `start'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/engine.rb:147:in `run'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:783:in `block in run_worker'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:1056:in `main_process'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:774:in `run_worker'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/command/fluentd.rb:370:in `<top (required)>'
  2023-05-15 14:13:11 +0000 [error]: #0 <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
  2023-05-15 14:13:11 +0000 [error]: #0 <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/bin/fluentd:15:in `<top (required)>'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/bin/fluentd:25:in `load'
  2023-05-15 14:13:11 +0000 [error]: #0 /usr/bin/fluentd:25:in `<main>'
```

**Fluentd CR doesn't have a `podSecutiryContext` nor an `initContainer` field to set broader container permissions**

Another problem I'm dealing with is that if a single buffer breaks all the others are compromised because fluentd pod gets in an error loop. Any hints on how to mitigate this?

### To Reproduce

Apply an Output or ClusterOutput with a file buffer:

```
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: cluster-output-opensearch
  labels:
    output.fluentd.fluent.io/enabled: "true"
    output.fluentd.fluent.io/tenant: "core"
spec:
  outputs:
    - customPlugin:
        config: |
          <match **>
            @type opensearch
            host XXXX
            port 443
            logstash_format  true
            logstash_prefix logs-buffer-file
            scheme https
            log_os_400_reason true
            @log_level trace
            <buffer>
              @type file
              path /data/fluentd/buffer.log
              flush_mode interval
              flush_interval 10s
              flush_thread_count 8
              flush_at_shutdown true
              chunk_limit_size 256m
              total_limit_size 10g
              overflow_action throw_exception
              retry_max_times 5
              retry_wait 30s
              retry_exponential_backoff_base 2
              retry_max_interval 90
              compress gzip
            </buffer>
            <endpoint>
              url "https://XXXX
              region XXX
              assume_role_arn "#{ENV['AWS_ROLE_ARN']}"
              assume_role_web_identity_token_file "#{ENV['AWS_WEB_IDENTITY_TOKEN_FILE']}"
            </endpoint>
          </match>
```

### Expected behavior

Be able to use file buffers without permission errrors on fluentd.

### Your Environment

```markdown
- Fluent Operator version: v2.1.1
- Container Runtime: Docker
- Operating system: Ubuntu
- Kernel version:
```

### How did you install fluent operator?

Via Helm Chart

**Comment by erhudy** [comment]
I ran into this and worked around it by patching `pkg/operator/sts.go` to set an fsGroup of 101 on the PodSecurityContext (101 is the fluentd group in the kubesphere fluentd container).

**Comment by benjaminhuo** [comment]
> I ran into this and worked around it by patching `pkg/operator/sts.go` to set an fsGroup of 101 on the PodSecurityContext (101 is the fluentd group in the kubesphere fluentd container).

Would you help to create a PR for this?

**Comment by erhudy** [comment]
Pushed a PR in #744.
